### ISSUE TITLE
I cant make sense out of the way you compile your applications

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [hanabi1224/Programming-Language-Benchmarks#197]
I can't make sense out of the way you execute these benchmarks. Here are a few things I noticed:

- https://github.com/hanabi1224/Programming-Language-Benchmarks/blob/56aee38efa03b60ed4d6655cf8935324a90cd65c/bench/bench_c.yaml
No optimization options applied, does not seem realistic at all

- https://github.com/hanabi1224/Programming-Language-Benchmarks/blob/56aee38efa03b60ed4d6655cf8935324a90cd65c/bench/bench_rust.yaml
Seems to be optimized for skylake instruction set?

- https://github.com/hanabi1224/Programming-Language-Benchmarks/blob/56aee38efa03b60ed4d6655cf8935324a90cd65c/bench/bench_java.yaml 
'Properly' benchmarking Java applications is a pain. First of all, you need to set `-Xmx`, `-Xms`, `-server`, `-Xbatch`, possibly I am missing a few options, then let JVM warmup by executing benchmark several times and only then run benchmarks (on the same JVM instance without stoping it). Or at least this is a way of benchmarking that is the most accurate for running applications in the cloud. But yes, this is not exactly easily changeable by the looks of current project structure

**Comment by hanabi1224** [comment]
> No optimization options applied, does not seem realistic at all

It's using [app.rsp](https://github.com/hanabi1224/Programming-Language-Benchmarks/blob/main/bench/include/c/app.rsp) as option provider

> Seems to be optimized for skylake instruction set?

Yes, all langs are using skylake as cpu target when applicable.

> 'Properly' benchmarking Java applications is a pain. 

Not using JMH here as the benchmark is designed to be language agnostic. Warmup is not that critical as these are toy programs instead of microbenchmarks,  java has a mature JIT engine with advanced PGO(profile-guided optimizations) to mitigate that, that's why helloworld in java / c# are much faster than in ruby with jit on

**Comment by gytis-ivaskevicius** [comment]
Yeah, I missed `app.rsp`, as for Java - 'eh, fair enough' :D 
Thanks for the info, and keep up the good work!
