### ISSUE TITLE
Boost library for c++?

### ISSUE THREAD

**Issue by bpecsek** [hanabi1224/Programming-Language-Benchmarks#225]
Could you please confirm if we could use Boost library for C++?

**Comment by JZerf** [comment]
I'm curious about whether this will be allowed too. It seems like it is more appropriate to treat Boost as a collection of separate libraries (although they're often all treated as one big library and installed all together). Some of the libraries like the one for atomics, threads, and coroutines do use a bit of assembly instructions so since they're not part of C++'s standard libraries and making use of a different programming language, I'm thinking those particular libraries should not be allowed according to [what I've heard so far](https://github.com/hanabi1224/Programming-Language-Benchmarks/issues/220#issuecomment-1003266231). It seems like most of the rest of the libraries could be OK.

**Comment by bpecsek** [comment]
I do agree with you but I have decided to ask everything from the maintainer.
However, at the moment it looks like he is not replying to me at all so I might just give up.
It feels terrible being treated like this. It feels like déjà vu coming from CLBG.

**Comment by bpecsek** [comment]
It looks like you stopped responding to me all together so I am closing this.
