### ISSUE TITLE
CPU Architecture

### ISSUE THREAD

**Issue by HenryJk** [hanabi1224/Programming-Language-Benchmarks#233]
Most programs are compiled targeting `broadwell` architecture even though the test hardware is `Xeon(R) Platinum 8272CL` which is `cascadelake`. The test hardware have `avx512` instruction set (and others) that doesn't usually exist in consumer level hardware (most dev machine). Is this intended e.g. to ease test and development of contributed programs?

**Comment by hanabi1224** [comment]
The test hardware is randomly chosen from a pool, from haswell to cascadelake. [GH action doc](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#cloud-hosts-for-github-hosted-runners), [Azure VM doc](https://docs.microsoft.com/en-us/azure/virtual-machines/dv2-dsv2-series#dsv2-series)

avx512 is an arguable feature, Intel might plan to [deprecate it](https://www.techpowerup.com/290460/intel-to-disable-rudimentary-avx-512-support-on-alder-lake-processors?cp=1#:~:text=Intel%27s%20reason%20to%20deprecate%20what%20little%20client-relevant%20AVX-512,markets.%20Many%20Thanks%20to%20TheoneandonlyMrK%20for%20the%20tip.). Also because of the power consumption, the CPU might end up running at a [reduced frequency](https://www.anandtech.com/show/16535/intel-core-i7-11700k-review-blasting-off-with-rocket-lake/2) with even worth performance when using avx512, so I don't plan to enable it.

**Comment by HenryJk** [comment]
That explains everything.

**Comment by igouy** [comment]
> randomly chosen from a pool

I'd like to know what hardware was used for the last run before Fri 28 Jan 2022 10∶19∶04 AM PST -- is that information available somewhere?

**Comment by hanabi1224** [comment]
Yes, u can check the `lscpu` section in the [CI log](https://github.com/hanabi1224/Programming-Language-Benchmarks/runs/4964850763?check_suite_focus=true), u can also download the benchmark result from build artifacts and generate the site snapshot locally
