### ISSUE TITLE
Zig Compiler is using edge (nightly) branch

### ISSUE THREAD

**Issue by HenryJk** [hanabi1224/Programming-Language-Benchmarks#238]
`sudo snap install zig --classic --edge`

should have been 

`sudo snap install zig --classic --beta`

for more stable branch.

**Comment by hanabi1224** [comment]
Thanks, but please note that `zig` is a pre-1.0 language, there're not too many differences between maintaining nightly and stable versions as it has a pretty good tracking record of maintaining API stability. And since its stable version does not guarantee API backward compatibility either, it either breaks now or later, I would just fix the code since it's never been too hard.
